version: '3'

services:
  backend:
    build:
      context: ./server
      dockerfile: ./server/Dockerfile
    image: "backend"
    ports:
      - "4000:4000"
  frontend:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: "frontend"
    ports:
      - "3000:3000"
    links:
      - "backend"